
export const GET_BOOK_REQUEST= "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS= "GET_BOOK_SUCCESS";
export const GET_BOOK_ERROR= "GET_BOOK_ERROR";

export const UPDATE_BOOK_REQUEST= "UPDATE_BOOK_REQUEST";
export const UPDATE_BOOK_SUCCESS= "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_ERROR= "UPDATE_BOOK_ERROR";

// export const CREATE_BOOK_REQUEST= "CREATE_BOOK_REQUEST";
// export const CREATE_BOOK_SUCCESS= "CREATE_BOOK_SUCCESS";
// export const CREATE_BOOK_ERROR= "CREATE_BOOK_ERROR";